config/routes.rb
# -*- encoding : utf-8 -*-
Gfp::Application.routes.draw do

  root to: "home#index"
  
  resource :sessions
  resources :usuarios

  match "sign_in" => "sessions#new"
  match "sign_up" => "usuarios#new"  
  match "profile_edit" => "usuarios#edit"
  match "profile_delete" => "usuarios#destroy"

  get  "password_reset/new"
  get  "password_reset/edit"
  post "password_reset/create"

end

app/models/session.rb
# -*- encoding : utf-8 -*-
class Session
	
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor :login_name, :password, :remember_me

	validates :login_name, :password, presence: true

	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=".to_sym, value)
		end
	end

	def persisted?
		false
	end

	def remember_me?
		remember_me == "1"
	end

end

app/models/usuario.rb
# -*- encoding : utf-8 -*-
class Usuario < ActiveRecord::Base

	has_secure_password

  attr_accessible :nome, :nome_login, :email, :password_digest, :password, :password_confirmation

  validates :nome,  :nome_login, :email, presence: true
  validates :nome_login, uniqueness: { message: "Nome de usuário já cadastrado!" }
  validates :email, uniqueness: { message: "E-mail já cadastrado!" }
  	
  validates_format_of :email, with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, message: "E-mail inválido!"

  before_create { generate_unique_random_token(:auth_token) }

  before_save { |u| 
    u.nome = u.nome.titleize
    u.email.downcase!
  }

	def self.login(usuario, senha)
		find(:first, conditions: ["nome_login = ? or email = ?", usuario, usuario]).try(:authenticate, senha)
	end

  def reset_password
    generate_unique_random_token(:password_reset_token)
    save
  end

  private

  def generate_unique_random_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64 + SecureRandom.urlsafe_base64
    end while Usuario.exists?(column => self[column])
  end

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  	
  	protect_from_forgery
  	
  	before_filter :need_login, unless: -> { 
      controller_name == "sessions" || 
      controller_name == "usuarios" && (action_name == "new" || action_name == "create" || action_name == "destroy") ||
      controller_name == "password_reset"
    }

    protected

    def need_login
      unless already_logged_in?
        session[:requested_url] = request.url
        redirect_to sign_in_path 
      end
    end

    def already_logged_in?
      !session[:user].nil?
    end

    def session_user
      session[:user]
    end

    def update_session_user(user)
      unless already_logged_in?
        session[:last_login] = user.ultimo_acesso
        user.password_reset_token = nil
        user.ultimo_acesso = Time.now
        user.save
      end

      session[:user] = user      
    end

    def remove_session_user
      session[:user] = nil
      session[:requested_url] = nil;
      session[:last_login] = nil;       
    end

end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController

  def index
  end

end

app/controllers/password_reset_controller.rb
# -*- encoding : utf-8 -*-
class PasswordResetController < ApplicationController

  def create
  	usuario = Usuario.find_by_email(params[:email])

    if usuario     
    	usuario.reset_password
	  	UsuarioMailer.mail_reset_senha(request, usuario).deliver
	  	redirect_to sign_in_path, flash: { notice: "As instruções para troca de sua senha foram enviadas para o e-mail #{params[:email]}" }
	  else
		  redirect_to password_reset_new_path, flash: { error: "E-mail não cadastrado!" }
  	end  	
  end

	def edit
		usuario = Usuario.find_by_password_reset_token(params[:id])

		if usuario
			update_session_user(usuario)
			redirect_to profile_edit_path(usuario)
		else
			remove_session_user
			redirect_to sign_in_path, flash: { error: "Código de autenticação inválido ou expirado!" }
		end
	end  

end

app/controllers/sessions_controller.rb
# -*- encoding : utf-8 -*-
class SessionsController < ApplicationController

	def new
		@session = Session.new
		usuario = Usuario.find_by_auth_token(cookies[:remember_me]) if cookies[:remember_me]

		if usuario
			@session.login_name = usuario.nome_login
			@session.password = "ztySUlt3b+mKPX3fcm"
			@session.remember_me = true
		end
	end

	def create
		@session = Session.new(params[:session])

		if @session.valid?
			usuario = Usuario.find_by_auth_token(cookies[:remember_me]) if @session.remember_me? && cookies[:remember_me]
			usuario ||= Usuario.login(@session.login_name, @session.password)

			cookies.delete(:remember_me) unless @session.remember_me?

			if usuario
				update_session_user(usuario)			
				cookies.permanent[:remember_me] = usuario.auth_token if @session.remember_me?	
				redirect_to session[:requested_url] || root_path
			else
				redirect_to sign_in_path, flash: { error: "Credenciais inválidas!" }
			end
		else
			render :new
		end
	end

	def destroy
		remove_session_user		
		redirect_to sign_in_path
	end

end

app/controllers/usuarios_controller.rb
# -*- encoding : utf-8 -*-
class UsuariosController < ApplicationController

	respond_to :html

	def new
		@usuario = Usuario.new
		respond_with @usuario
	end

	def edit
		@usuario = session_user
	end

	def create
		@usuario = Usuario.new(params[:usuario])

		if @usuario.save
			update_session_user(@usuario)
			UsuarioMailer.mail_boas_vindas(request, @usuario).deliver
			redirect_to root_path
		else
			render :new
		end
	end

	def update
		@usuario = session_user

		if @usuario.update_attributes(params[:usuario])
			update_session_user(@usuario)
			redirect_to root_path, flash: { success: "Seu perfil foi atualizado com sucesso!" }
		else
			render :edit
		end
	end

	def destroy
		@usuario = session_user
		@usuario.destroy
		remove_session_user
		redirect_to sign_in_path, flash: { success: "Seu perfil foi excluído com sucesso! Obrigado por utilizar o GFP." }
	end

end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper

	def flash_type(type)
		result = "fade in alert alert-"

	  case type
	    when :alert
	      result + "warning"
	    when :error
	      result + "error"
	    when :notice
	      result + "info"
	    when :success
	      result + "success"
	    else
	      type.to_s
	  end
	end

	def link_to_delete(title, action, hint, message, sub=nil)
		message = "#{message}<p><small><i>#{sub}</i></small>" if sub 
		link_to " #{title}", action, rel: "popover", title: "#{title}", "data-content" => "#{hint}", class: "icon-trash", confirm: "#{message}"		
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_reset_helper.rb
# -*- encoding : utf-8 -*-
module PasswordResetHelper
end

app/helpers/passwords_helper.rb
# -*- encoding : utf-8 -*-
module PasswordsHelper
end

app/helpers/session_helper.rb
# -*- encoding : utf-8 -*-
module SessionHelper
end

app/helpers/usuarios_helper.rb
# -*- encoding : utf-8 -*-
module UsuariosHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>GFP - Gerente Financeiro Pessoal</title>
	  <%= favicon_link_tag       "/images/favicon.ico" %>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div class="container top">
			<div><%= link_to image_tag("/images/logo.png"), controller: "home" %></div>
			<div>
				<h1>GFP</h1>
				<h3 class="lead">Gerente Financeiro Pessoal</h3>
			</div>
			
			<% if session[:user] %>
				<div class="user-info">
					<span>Olá <%= session[:user].nome %>!</span><br/>
					<% if session[:last_login] %>
						<sub>Seu último acesso foi em: <%= session[:last_login].strftime("%d/%m/%Y às %H:%M") %></sub>
					<% end %>
					<br/>
					<hr/>					
					<%= link_to " Meu Perfil", profile_edit_path(session[:user]), class: "icon-user" %>
					|
					<%= link_to " Sair", sessions_path, method: :delete, class: "icon-off" %>
				</div>
			<% end %>							
		</div>

		<div class="container body">
			<% flash.each do |type, message| %>
				<% if flash[type] %>
					<div class="<%= flash_type(type) %>">
						<button class="close" data-dismiss="alert">&times;</button>
						<%= message %>
					</div>
				<% end %>
			<% end %>			
		
			<%= yield %>
		</div>

		<div class="container footer">
			<sub>Gerente Financeiro Pessoal - Copyright &copy; <%= Date.today.year %></sub>
		</div>
	</body>
</html>

app/views/password_reset/new.html.erb
<div class="row password-reset-container">
	<div class="span4 offset4">
		<%= form_tag(password_reset_create_path, class: "well") do %>
			<legend>Redefinição de Senha</legend>
			<img class="form-icon" src="/images/mail.png"/>
			<div class="input-append">
				<%= text_field_tag :email, nil, class: "span3", placeholder: "Enviar instruções de alteração para o e-mail" %><%= submit_tag "Enviar", class: "btn btn-success", style: "height: 28px" %>
			</div>
		<% end %>
	</div>
</div>

app/views/usuarios/_form.html.erb
<div class="row usuarios-container">
	<div class="span4 offset4">
		<%= simple_form_for @usuario, html: { class: "well span3" } do |f| %>
			<legend>Meu Perfil</legend>
			<img class="form-icon" src="/images/user.png"/>
			<%= f.input :nome, autofocus: true, input_html: { class: "span3" } %>
			<%= f.input :nome_login, label: "Nome de Usuário", disabled: !@usuario.id.nil?, input_html: { class: "span3" } %>
			<%= f.input :email, label: "E-mail", disabled: !@usuario.id.nil?, input_html: { class: "span3" } %>
			<%= f.input :password, label: "Senha", input_html: { class: "span3" } %>
			<%= f.input :password_confirmation, label: "Confirmação", input_html: { class: "span3" } %>
			<% if @usuario.id.nil? %>
				<%= f.submit "Criar minha conta", class: "btn btn-success btn-large" %>
			<% else%>
				<%= f.submit "Gravar", class: "btn btn-primary" %>
				ou
				<%= link_to "Cancelar", root_path %>
				<br><br>		
				<%= link_to_delete "Excluir Perfil", profile_delete_path, "Clique aqui para cancelar sua conta do GFP e apagar todos os seus dados", "Deseja realmente excluir seu perfil do GFP?", "* Todas as suas informações também serão excluídas." %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/usuarios/edit.html.erb
<%= render "form" %>

app/views/usuarios/new.html.erb
<%= render "form" %>